language: node_js
node_js:
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g grunt-cli
before_script:
  - "cp src/js/config-example.js src/js/config.js"
  - "cp config-example.json config.json"
script: "grunt && ./node_modules/.bin/karma start test/karma.conf.js --single-run --browsers Firefox"
notifications:
  email:
    false
