language: node_js
node_js:
  - "0.10"
addons:
  hosts:
    - ripp.site
#addons:
#  sauce_connect: true
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update -qq
  - curl http://nginx.org/keys/nginx_signing.key | sudo apt-key add -
  - echo "deb http://nginx.org/packages/ubuntu/ precise nginx" | sudo tee -a /etc/apt/sources.list
  - echo "deb-src http://nginx.org/packages/ubuntu/ precise nginx" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install nginx
  - sudo nginx -s stop
  - npm install -g gulp
  - echo "$TRAVIS_BUILD_DIR"
  - echo "$SAUCE_USERNAME"
  - cd test/sauce && npm install
  - node launch_connect.js &
  - $TRAVIS_BUILD_DIR/test/sauce/wait_for_browser_provider.sh
  - cd $TRAVIS_BUILD_DIR
before_script:
  - "cp test/travis/config-travis.js config.js"
  - "cp test/travis/ripple-travis.txt ripple.txt"
  - npm install -g bower
  - bower install
  - npm install -g darkdarkdragon/se-interpreter
  - sudo nginx -c "$TRAVIS_BUILD_DIR/test/travis/nginx.conf"
  - curl -i http://localhost:9002
  - sudo ps aux
  - sudo ls -l /proc/*/exe || true
script: "./test/travis-run.sh"
after_script:
  - curl -i http://localhost:3000/config.js
  - curl -i http://localhost:3000/ripple.txt
notifications:
  email:
    false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/706809d6a4c29c8fb8b6
    on_success: change
    on_failure: always
    on_start: false
env:
  global: 
    - SAUCE_CONNECT_VERSION=4.3.8
    - SAUCE_USERNAME=tonga
    - SAUCE_ACCESS_KEY=***REMOVED***
    - secure: "g+bSaoKAx6YQTVof5kUBdWx/REaKzqzkP+CQqsU6Whx+rp9juOtJGNtfH++PaWP1hSslRJi2Ib+9+/EU6CXzLE6IlwLHcnBikexeeF28kEivwRqxosLERLQ0axk8VGw324kgUDG1DsJNKxZFPq+LlXkPcF5eVta+BcSz5BO2ygs="
    - secure: "BIFtSHbHke2SfyhCTjnSVwkQ3g8aGGV9ZR+tTSFQmp5RVMPEPTy0eiLx4qk+D/UTnJztQSqrtecVvhIa1iHtkwqecyS3/Hjs5h3F9pHNVdL5njk+sMcI4qL63ijpSG3j41jG81SHiCUi86u0FpGtrYzUaSBVe/DWEKwyXmYMlrM="
#    - secure: "VJFHj5fr46Qf7h34xa/W6FmGvknPH57eQLJoEjKlZUYn0EGx9EliCdENfzAbtr3e4GnNvQh6X2bLA/lB7TRzoD84oyGkllkMayevQm/dViJbUBQsl7HOa6VwUwugW+o7T3+vPM4y5qqFv1B/fs3Fthl+eKUatccy9qK4xra1Hso="


